BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "refVendors" (
	"id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Notes"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "wrkEvents" (
	"id"	INTEGER NOT NULL,
	"Type"	TEXT NOT NULL,
	"idPart"	INTEGER NOT NULL,
	"DateTime"	TEXT NOT NULL,
	"Qty"	NUMERIC NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idPart") REFERENCES "refParts"("id")
);
CREATE TABLE IF NOT EXISTS "refParts" (
	"id"	INTEGER NOT NULL,
	"idCategory"	INTEGER NOT NULL,
	"idVendor"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Notes"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idCategory") REFERENCES "refCategories"("id"),
	FOREIGN KEY("idVendor") REFERENCES "refVendors"("id")
);
CREATE TABLE IF NOT EXISTS "refCategories" (
	"id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Notes"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
