BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "refTypeParts" (
	"id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Notes"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "refVendors" (
	"id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Notes"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "refParts" (
	"id"	INTEGER NOT NULL,
	"idType"	INTEGER NOT NULL,
	"idVendor"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Notes"	TEXT NOT NULL,
	FOREIGN KEY("idType") REFERENCES "refTypeParts"("id"),
	FOREIGN KEY("idVendor") REFERENCES "refVendors"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "wrkEvents" (
	"id"	INTEGER NOT NULL,
	"Type"	TEXT NOT NULL,
	"idPart"	INTEGER NOT NULL,
	"DateTime"	REAL NOT NULL,
	"Qty"	NUMERIC NOT NULL,
	FOREIGN KEY("idPart") REFERENCES "refParts"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;